package com.example.hereapp.data

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class ContactDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var contactDao: ContactDao

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        contactDao = database.contactDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun insert_returnsAutoGeneratedId() = runBlocking {
        val id = contactDao.insert(Contact(name = "Alice", phone = "555-1234"))
        assertTrue(id > 0)
    }

    @Test
    fun insert_secondContact_getsHigherId() = runBlocking {
        val id1 = contactDao.insert(Contact(name = "Alice", phone = "555-1234"))
        val id2 = contactDao.insert(Contact(name = "Bob", phone = "555-5678"))
        assertTrue(id2 > id1)
    }

    @Test
    fun getContactById_existingContact_returnsContact() = runBlocking {
        val id = contactDao.insert(Contact(name = "Alice", phone = "555-1234"))
        val contact = contactDao.getContactById(id)
        assertNotNull(contact)
        assertEquals("Alice", contact!!.name)
        assertEquals("555-1234", contact.phone)
        assertEquals(id, contact.id)
    }

    @Test
    fun getContactById_nonExistent_returnsNull() = runBlocking {
        val contact = contactDao.getContactById(999)
        assertNull(contact)
    }

    @Test
    fun getAllContacts_emptyDatabase_returnsEmptyList() = runBlocking {
        val contacts = contactDao.getAllContacts().first()
        assertTrue(contacts.isEmpty())
    }

    @Test
    fun getAllContacts_returnsAllInserted() = runBlocking {
        contactDao.insert(Contact(name = "Alice", phone = "555-1111"))
        contactDao.insert(Contact(name = "Bob", phone = "555-2222"))
        contactDao.insert(Contact(name = "Charlie", phone = "555-3333"))
        val contacts = contactDao.getAllContacts().first()
        assertEquals(3, contacts.size)
    }

    @Test
    fun getAllContacts_orderedByNameAsc() = runBlocking {
        contactDao.insert(Contact(name = "Charlie", phone = "555-3333"))
        contactDao.insert(Contact(name = "Alice", phone = "555-1111"))
        contactDao.insert(Contact(name = "Bob", phone = "555-2222"))
        val contacts = contactDao.getAllContacts().first()
        assertEquals("Alice", contacts[0].name)
        assertEquals("Bob", contacts[1].name)
        assertEquals("Charlie", contacts[2].name)
    }

    @Test
    fun update_changesContactFields() = runBlocking {
        val id = contactDao.insert(Contact(name = "Alice", phone = "555-1234"))
        val contact = contactDao.getContactById(id)!!
        contactDao.update(contact.copy(name = "Alicia", phone = "555-9999"))
        val updated = contactDao.getContactById(id)
        assertEquals("Alicia", updated!!.name)
        assertEquals("555-9999", updated.phone)
    }

    @Test
    fun delete_removesContact() = runBlocking {
        val id = contactDao.insert(Contact(name = "Alice", phone = "555-1234"))
        val contact = contactDao.getContactById(id)!!
        contactDao.delete(contact)
        val result = contactDao.getContactById(id)
        assertNull(result)
    }

    @Test
    fun delete_removesFromGetAll() = runBlocking {
        contactDao.insert(Contact(name = "Alice", phone = "555-1111"))
        val id2 = contactDao.insert(Contact(name = "Bob", phone = "555-2222"))
        val toDelete = contactDao.getContactById(id2)!!
        contactDao.delete(toDelete)
        val contacts = contactDao.getAllContacts().first()
        assertEquals(1, contacts.size)
        assertEquals("Alice", contacts[0].name)
    }
}
