package com.example.hereapp.data

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class MessageDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var messageDao: MessageDao

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        messageDao = database.messageDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun insert_returnsAutoGeneratedId() = runBlocking {
        val id = messageDao.insert(Message(text = "Hello"))
        assertTrue(id > 0)
    }

    @Test
    fun insert_secondMessage_getsHigherId() = runBlocking {
        val id1 = messageDao.insert(Message(text = "First"))
        val id2 = messageDao.insert(Message(text = "Second"))
        assertTrue(id2 > id1)
    }

    @Test
    fun getMessageById_existingMessage_returnsMessage() = runBlocking {
        val id = messageDao.insert(Message(text = "Hello"))
        val message = messageDao.getMessageById(id)
        assertNotNull(message)
        assertEquals("Hello", message!!.text)
        assertEquals(id, message.id)
    }

    @Test
    fun getMessageById_nonExistent_returnsNull() = runBlocking {
        val message = messageDao.getMessageById(999)
        assertNull(message)
    }

    @Test
    fun getAllMessages_emptyDatabase_returnsEmptyList() = runBlocking {
        val messages = messageDao.getAllMessages().first()
        assertTrue(messages.isEmpty())
    }

    @Test
    fun getAllMessages_returnsAllInserted() = runBlocking {
        messageDao.insert(Message(text = "First"))
        messageDao.insert(Message(text = "Second"))
        messageDao.insert(Message(text = "Third"))
        val messages = messageDao.getAllMessages().first()
        assertEquals(3, messages.size)
    }

    @Test
    fun getAllMessages_orderedByIdAsc() = runBlocking {
        val id1 = messageDao.insert(Message(text = "First"))
        val id2 = messageDao.insert(Message(text = "Second"))
        val id3 = messageDao.insert(Message(text = "Third"))
        val messages = messageDao.getAllMessages().first()
        assertEquals(id1, messages[0].id)
        assertEquals(id2, messages[1].id)
        assertEquals(id3, messages[2].id)
    }

    @Test
    fun update_changesMessageText() = runBlocking {
        val id = messageDao.insert(Message(text = "Original"))
        val message = messageDao.getMessageById(id)!!
        messageDao.update(message.copy(text = "Updated"))
        val updated = messageDao.getMessageById(id)
        assertEquals("Updated", updated!!.text)
    }

    @Test
    fun delete_removesMessage() = runBlocking {
        val id = messageDao.insert(Message(text = "To delete"))
        val message = messageDao.getMessageById(id)!!
        messageDao.delete(message)
        val result = messageDao.getMessageById(id)
        assertNull(result)
    }

    @Test
    fun delete_removesFromGetAll() = runBlocking {
        val id1 = messageDao.insert(Message(text = "Keep"))
        val id2 = messageDao.insert(Message(text = "Delete"))
        val toDelete = messageDao.getMessageById(id2)!!
        messageDao.delete(toDelete)
        val messages = messageDao.getAllMessages().first()
        assertEquals(1, messages.size)
        assertEquals(id1, messages[0].id)
    }
}
